#!/bin/sh
#
# @name Heligyro (NN Control Ready)
# @type MC
#
# ============================================================================
# HELIGYRO - Neural Network Offboard Control (Minimal Working Version)
# ============================================================================

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=heligyro}

param set-default MAV_TYPE 196
set SYS_AUTOSTART 5230

# ---------------------------------------------------------------------------
# SIMULATION SETTINGS
# ---------------------------------------------------------------------------
param set-default SIM_GZ_EN 1
param set-default SIM_BAT_ENABLE 1
param set-default SIM_BAT_DRAIN 600.0
param set-default SENS_EN_ARSPDSIM 1

# ---------------------------------------------------------------------------
# OFFBOARD ACTUATOR SET CONFIGURATION (Direct Motor Control)
# ---------------------------------------------------------------------------
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105

param set-default SIM_GZ_EC_MIN1 0.0
param set-default SIM_GZ_EC_MAX1 438.0
param set-default SIM_GZ_EC_MIN2 -1300.0
param set-default SIM_GZ_EC_MAX2 1300.0
param set-default SIM_GZ_EC_MIN3 -1300.0
param set-default SIM_GZ_EC_MAX3 1300.0
param set-default SIM_GZ_EC_MIN4 -1300.0
param set-default SIM_GZ_EC_MAX4 1300.0
param set-default SIM_GZ_EC_MIN5 -1300.0
param set-default SIM_GZ_EC_MAX5 1300.0

# ---------------------------------------------------------------------------
# ENABLE DYNAMIC CONTROL ALLOCATION (Critical!)
# ---------------------------------------------------------------------------
param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 5
param set-default CA_SV_CS_COUNT 0

# ---------------------------------------------------------------------------
# ARMING & FAILSAFE
# ---------------------------------------------------------------------------
param set-default COM_RC_IN_MODE 4
param set-default COM_OF_LOSS_T 30.0
param set-default COM_RC_LOSS_T 10.0
param set-default FD_ACT_EN 0

# Disable arming checks
param set-default COM_ARM_EKF_POS 0
param set-default COM_ARM_EKF_VEL 0
param set-default COM_ARM_EKF_HGT 0
param set-default COM_ARM_EKF_YAW 0
param set-default COM_ARM_IMU_ACC 0
param set-default COM_ARM_IMU_GYR 0
param set-default CBRK_SUPPLY_CHK 894281
param set-default CBRK_IO_SAFETY 22027
param set-default COM_ARMABLE 1

# ---------------------------------------------------------------------------
# MISSION & NAVIGATION
# ---------------------------------------------------------------------------
param set-default MIS_TAKEOFF_ALT 2.0
param set-default NAV_ACC_RAD 10

# ---------------------------------------------------------------------------
# HELIGYRO SPECIFIC
# ---------------------------------------------------------------------------
param set-default MC_AIRMODE 1
